nginx-proxy:  
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /home/ubuntu/resumesite/website:/usr/share/nginx/html:ro
    - /home/ubuntu/certs:/etc/nginx/certs
    - /home/ubuntu/resumesite/default:/etc/nginx/sites-enabled/default
  restart: always
